### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by JerryWho** [trevorstephens/titanic#1]
Hi,

is it allowed to put the data from https://campus.datacamp.com/courses/kaggle-r-tutorial-on-machine-learing/chapter-1-raising-anchor?ex=2 into this repository?

Cheers,
JW

**Comment by trevorstephens** [comment]
Hi @JerryWho , it appears DataCamp has taken the data from Kaggle and put it on their own servers, which I believe is against the Kaggle terms of service. So I would recommend getting the data from Kaggle yourself, as you'll need an account there to submit your predictions anyhow.
